[package]
name = "hyperloglog-rs"
version = "0.1.56"
edition = "2021"
authors = ["Luca Cappelletti <cappelletti.luca94@gmail.com>"]
description = "A Rust implementation of HyperLogLog trying to be parsimonious with memory."
homepage = "https://github.com/LucaCappelletti94/hyperloglog-rs"
repository = "https://github.com/LucaCappelletti94/hyperloglog-rs"
readme = "README.md"
license = "MIT"
keywords = ["hyperloglog", "probabilistic", "algorithm", "cardinality", "estimation",]
categories = [
    "no-std",
    "algorithms",
    "science"
]
exclude = [
    "fuzz/",
    "intersection_tests/",
    "union_test",
    "experiments",
    "intersection_benchmarks.tsv.gz"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
paste = "1.0.15"
twox-hash = {version="1.6.3", default-features = false}
mem_dbg = {version = "0.2.2", optional = true}

[dev-dependencies]
serde_json = "1.0"
rand = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
hyperloglogplus = {git = "https://github.com/LucaCappelletti94/hyperloglog.rs.git", branch = "mem_dbg"}
streaming_algorithms = {git = "https://github.com/LucaCappelletti94/streaming_algorithms", branch = "mem_dbg"}
cardinality-estimator = {git = "https://github.com/LucaCappelletti94/cardinality-estimator.git", branch = "mem_dbg"}
rust-hyperloglog = {git = "https://github.com/LucaCappelletti94/rust-hyperloglog.git", branch = "updated_siphasher", package = "hyperloglog"}
stattest = {git = "https://github.com/LucaCappelletti94/stattest"}
csv = "1.3.0"

[features]
default = ["serde", "std", "mem_dbg"]
std = [
    "twox-hash/std",
]
mem_dbg = [
    "dep:mem_dbg",
    "streaming_algorithms/mem_dbg",
    "hyperloglogplus/mem_dbg",
    "cardinality-estimator/mem_dbg",
    "rust-hyperloglog/mem_dbg",
]
alloc = []

[profile.test]
overflow-checks = true   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = true  # Enables debug assertions.
opt-level = 3

[profile.release]
overflow-checks = false   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = false  # Enables debug assertions.
opt-level = 3

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "cardinality"
harness = false

[[bench]]
name = "union"
harness = false

[[bench]]
name = "hash_functions"
harness = false

[[bench]]
name = "exp2"
harness = false
