[package]
name = "hyperloglog-rs"
version = "0.1.7"
edition = "2021"
authors = ["Luca Cappelletti <cappelletti.luca94@gmail.com>"]
description = "A Rust implementation of HyperLogLog trying to be parsimonious with memory."
homepage = "https://github.com/LucaCappelletti94/hyperloglog-rs"
repository = "https://github.com/LucaCappelletti94/hyperloglog-rs"
readme = "README.md"
license = "MIT"
keywords = ["hyperloglog", "probabilistic", "algorithm", "cardinality", "estimation",]
categories = [
    "Data structures",
    "Algorithms",
    "Mathematics",
    "Performance and optimization",
    "Probability and statistics",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
siphasher = "0.3"

[profile.test]
overflow-checks = true   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = true  # Enables debug assertions.
opt-level = 3

[profile.release]
overflow-checks = false   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = true  # Enables debug assertions.
opt-level = 3
