//! Generator for the dense register-regime bias-correction coefficients and the linear-counting
//! thresholds written to `../src/correction_coefficients.rs`.
#![deny(unsafe_code)]
#![deny(unused_macro_rules)]
#![deny(missing_docs)]
extern crate prettyplease;
extern crate proc_macro2;
extern crate quote;
extern crate syn;

use correction_coefficients::utils;

use prettyplease::unparse;
use proc_macro2::TokenStream;
use quote::quote;
use syn::File;

use crate::utils::{register_correction, CorrectionPerformance, RegisterCorrection};
use hyperloglog_rs::prelude::*;
use indicatif::MultiProgress;
use indicatif::{ProgressBar, ProgressStyle};
use test_utils::prelude::write_report;

/// Procedural macro to generate the correction function for the provided precision,
/// and bit sizes.
macro_rules! generate_gap_for_precision {
    ($reports:ident, $multiprogress:ident, $precision:ty, $($bit_size:ty),*) => {
        let progress_bar = $multiprogress.add(ProgressBar::new(3 as u64));

        progress_bar.set_style(
            ProgressStyle::default_bar()
                .template("Bits: [{elapsed_precise} | {eta}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
                .unwrap()
                .progress_chars("##-"),
        );

        progress_bar.tick();

        $(
            let report = register_correction::<$precision, $bit_size>($multiprogress);
            $reports.push(report);
            progress_bar.inc(1);
        )*

        progress_bar.finish_and_clear();
    };
}

/// Procedural macro to generate the correction function for the provided precisions.
macro_rules! generate_gap_for_precisions {
    ($reports:ident, $multiprogress:ident, $($precision:ty),*) => {
        let progress_bar = $multiprogress.add(ProgressBar::new(15));

        progress_bar.set_style(
            ProgressStyle::default_bar()
                .template("Precisions: [{elapsed_precise} | {eta}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
                .unwrap()
                .progress_chars("##-"),
        );

        progress_bar.tick();

        $(
            generate_gap_for_precision!($reports, $multiprogress, $precision, Bits4, Bits5, Bits6);
            progress_bar.inc(1);
        )*

        progress_bar.finish_and_clear();
    };
}

fn correction() {
    let mut reports: Vec<(RegisterCorrection, CorrectionPerformance)> = Vec::new();
    let multiprogress = &MultiProgress::new();
    generate_gap_for_precisions!(
        reports,
        multiprogress,
        Precision4,
        Precision5,
        Precision6,
        Precision7,
        Precision8,
        Precision9,
        Precision10,
        Precision11,
        Precision12,
        Precision13,
        Precision14,
        Precision15,
        Precision16,
        Precision17,
        Precision18
    );
    multiprogress.clear().unwrap();

    let path = "correction.csv";

    write_report(reports.iter().map(|(_, c)| c), path);

    let maximal_precision = reports.iter().map(|(c, _)| c.precision).max().unwrap();

    // Emit the linear-counting threshold per (P, B) cell. The dense register-regime bias
    // correction is now Ertl's analytical tau/sigma estimator (`src/sigma_tau.rs`), so this file
    // no longer emits polynomial coefficients or a domain table.
    let mut linear_count_thresholds: Vec<TokenStream> = Vec::new();

    (4..=maximal_precision).for_each(|exponent| {
        let mut this_linear_count_thresholds: Vec<TokenStream> = Vec::new();

        (4..=6).for_each(|bit_size| {
            let (correction, _) = reports
                .iter()
                .find(|(correction, _)| {
                    correction.precision == exponent && correction.bits == bit_size
                })
                .unwrap();
            let sub_linear_count_threshold = correction.linear_count_threshold;
            this_linear_count_thresholds.push(quote! { #sub_linear_count_threshold });
        });

        linear_count_thresholds.push(quote! { [#(#this_linear_count_thresholds),*] });
    });

    let number_of_precisions = linear_count_thresholds.len();

    let output = quote! {
        //! Register-regime linear-counting threshold (generated by the `correction_coefficients` crate).
        //!
        //! The dense HyperLogLog register regime uses Ertl's analytical tau/sigma estimator in
        //! `src/sigma_tau.rs` (no fitted polynomials, no anchor tables). What remains here is the
        //! per-cell linear-counting crossover: below this cardinality the counter stays in the
        //! NaN-boxed dense zeros mode and returns `m * ln(m / zeros)` in O(1); above it, `to_hll`
        //! and the insert path transition to the packed harmonic mode where sigma/tau applies.
        //!
        //! The hash-list regime is estimated analytically by the width-aware occupancy inverse in
        //! `src/hyperloglog.rs` (`HyperLogLog::hash_list_cardinality`).

        /// The cardinality at or below which a force-dense HyperLogLog counter should report linear
        /// counting instead of Ertl's tau/sigma estimate, indexed `[precision - 4][bits - 4]`.
        pub(super) const HYPERLOGLOG_LINEAR_COUNT_THRESHOLD: [[u32; 3]; #number_of_precisions] = [
            #(#linear_count_thresholds),*
        ];
    };

    // We write out the output token stream to '../src/composite_hash/gap_birthday_paradox.rs'
    let output_path = "../src/correction_coefficients.rs";

    // Convert the generated TokenStream to a string
    let code_string = output.to_string();

    // Parse the generated code string into a syn::Item
    let syntax_tree: File = syn::parse_str(&code_string).unwrap();

    // Use prettyplease to format the syntax tree
    let formatted_code = unparse(&syntax_tree);

    // Write the formatted code to the output file
    std::fs::write(output_path, formatted_code).unwrap();

    println!("Generated correction coefficients in '{}'", output_path);
}

fn main() {
    correction();
}
