//! Generator for the per-cell linear-counting thresholds emitted at
//! `../src/correction_coefficients.rs`. The dense register-regime bias correction is Ertl's
//! analytical tau/sigma estimator (`src/sigma_tau.rs`), so this generator no longer fits
//! polynomials or emits an anchor table; it only pins down where linear counting stops beating
//! sigma/tau, cell by cell.
#![deny(unsafe_code)]
#![deny(unused_macro_rules)]
#![deny(missing_docs)]
extern crate prettyplease;
extern crate proc_macro2;
extern crate quote;
extern crate syn;

use correction_coefficients::utils;

use prettyplease::unparse;
use proc_macro2::TokenStream;
use quote::quote;
use syn::File;

use crate::utils::{register_correction, RegisterCorrection};
use hyperloglog_rs::prelude::*;
use indicatif::MultiProgress;
use indicatif::{ProgressBar, ProgressStyle};

/// Runs `register_correction` for every `(precision, bits)` pair listed.
macro_rules! generate_gap_for_precision {
    ($corrections:ident, $multiprogress:ident, $precision:ty, $($bit_size:ty),*) => {
        let progress_bar = $multiprogress.add(ProgressBar::new(3 as u64));

        progress_bar.set_style(
            ProgressStyle::default_bar()
                .template("Bits: [{elapsed_precise} | {eta}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
                .unwrap()
                .progress_chars("##-"),
        );

        progress_bar.tick();

        $(
            let correction = register_correction::<$precision, $bit_size>($multiprogress);
            $corrections.push(correction);
            progress_bar.inc(1);
        )*

        progress_bar.finish_and_clear();
    };
}

/// Runs `generate_gap_for_precision` for every precision listed.
macro_rules! generate_gap_for_precisions {
    ($corrections:ident, $multiprogress:ident, $($precision:ty),*) => {
        let progress_bar = $multiprogress.add(ProgressBar::new(15));

        progress_bar.set_style(
            ProgressStyle::default_bar()
                .template("Precisions: [{elapsed_precise} | {eta}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
                .unwrap()
                .progress_chars("##-"),
        );

        progress_bar.tick();

        $(
            generate_gap_for_precision!($corrections, $multiprogress, $precision, Bits4, Bits5, Bits6);
            progress_bar.inc(1);
        )*

        progress_bar.finish_and_clear();
    };
}

fn correction() {
    let mut corrections: Vec<RegisterCorrection> = Vec::new();
    let multiprogress = &MultiProgress::new();
    generate_gap_for_precisions!(
        corrections,
        multiprogress,
        Precision4,
        Precision5,
        Precision6,
        Precision7,
        Precision8,
        Precision9,
        Precision10,
        Precision11,
        Precision12,
        Precision13,
        Precision14,
        Precision15,
        Precision16,
        Precision17,
        Precision18
    );
    multiprogress.clear().unwrap();

    let maximal_precision = corrections.iter().map(|c| c.precision).max().unwrap();

    // Emit the linear-counting threshold per (P, B) cell.
    let mut linear_count_thresholds: Vec<TokenStream> = Vec::new();

    (4..=maximal_precision).for_each(|exponent| {
        let mut this_linear_count_thresholds: Vec<TokenStream> = Vec::new();

        (4..=6).for_each(|bit_size| {
            let correction = corrections
                .iter()
                .find(|correction| correction.precision == exponent && correction.bits == bit_size)
                .unwrap();
            let threshold = correction.linear_count_threshold;
            this_linear_count_thresholds.push(quote! { #threshold });
        });

        linear_count_thresholds.push(quote! { [#(#this_linear_count_thresholds),*] });
    });

    let number_of_precisions = linear_count_thresholds.len();

    let output = quote! {
        //! Register-regime linear-counting threshold (generated by the `correction_coefficients` crate).
        //!
        //! The dense `HyperLogLog` register regime uses Ertl's analytical tau/sigma estimator in
        //! `src/sigma_tau.rs` (no fitted polynomials, no anchor tables). What remains here is the
        //! per-cell linear-counting crossover: below this cardinality the counter stays in the
        //! NaN-boxed dense zeros mode and returns `m * ln(m / zeros)` in O(1); above it, `to_hll`
        //! and the insert path transition to the packed harmonic mode where sigma/tau applies.
        //!
        //! The hash-list regime is estimated analytically by the width-aware occupancy inverse in
        //! `src/hyperloglog.rs` (`HyperLogLog::hash_list_cardinality`).

        /// The cardinality at or below which a force-dense HyperLogLog counter should report linear
        /// counting instead of Ertl's tau/sigma estimate, indexed `[precision - 4][bits - 4]`.
        pub(super) const HYPERLOGLOG_LINEAR_COUNT_THRESHOLD: [[u32; 3]; #number_of_precisions] = [
            #(#linear_count_thresholds),*
        ];
    };

    let output_path = "../src/correction_coefficients.rs";
    let code_string = output.to_string();
    let syntax_tree: File = syn::parse_str(&code_string).unwrap();
    let formatted_code = unparse(&syntax_tree);
    std::fs::write(output_path, formatted_code).unwrap();

    println!("Generated linear-counting thresholds in '{}'", output_path);
}

fn main() {
    correction();
}
