"""Python script to load and plot the reports generated by the measure_variant script.

The two reports, namely 'latest_report.csv' and 'reference_report.csv', contain a single
column with the relative error of respectively the latest and reference variants.

"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


def plot_all():
    """Load the reports and plot the histograms, boxplots and relative error plots."""
    # Load the reports
    latest_report = pd.read_csv("latest_report.csv")
    reference_report = pd.read_csv("reference_report.csv")

    latest_report.sort_values(by="cardinality", inplace=True)
    reference_report.sort_values(by="cardinality", inplace=True)

    fig, axs = plt.subplots(1, 1, figsize=(10, 5))

    axs.plot(
        latest_report.cardinality,
        latest_report.relative_error,
        label="Latest"
    )
    axs.plot(
        reference_report.cardinality,
        reference_report.relative_error, label="Reference", linestyle="--", alpha=0.7
    )

    axs.set_title("Relative error")
    axs.set_xlabel("Cardinality")
    axs.set_ylabel("Relative error")
    axs.legend()

    fig.tight_layout()
    fig.savefig("comparison.png")


if __name__ == "__main__":
    plot_all()
