# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy"]
# ///
"""Validate a CLOSED-FORM width-aware occupancy inverse against the probe data.

The SwitchHash composite at width w (hash_bits) is index (P uniform bits) followed by a
tail of t = w - P bits encoding the register (geometric leading-zero count) and residual:

  smallest width t == B:  cell = (index, register), register capped at R = 2^B - 1
      per-index tail mass: q(r) = 2^-r for r in 1..R-1, q(R) = 2^-(R-1) (absorbs the tail)

  wider width t > B:      tail = flag bit + (register or leading bits) + residual
      flag 0 (register <= B+1): the (t-1) leading hash bits stored verbatim,
          so every such cell has q = 2^-(t-1); grouped by leading-zero run l = 0..min(B, t-2)
      flag 1 (register >= B+2): register in B bits + residual of (t-1-B) bits,
          per residual cell q(r) = 2^-r * 2^-(t-1-B); r in B+2..2^B-2, plus a saturating
          cell at r = 2^B-1 absorbing sum_{r>=2^B-1} 2^-r = 2^-(2^B-2)

Expected distinct composites for n elements (all 2^P indices symmetric):
  E[D | n, w] = 2^P * sum_j count_j * (1 - (1 - 2^-P * q_j)^n)

We invert this monotone curve for n given the observed D = number_of_hashes, per row at the
row's own width, and compare to the true cardinality.

The derivation above is the reference cited by `HyperLogLog::hash_list_cardinality`. The validation
arm below reads a probe CSV of measured trajectories that is not committed (it is regenerated by a
sampling sweep), so running the validation requires producing that CSV first.
"""

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
CSV = HERE / "duplicates_probe.csv"


def tail_groups(P, B, w):
    """List of (count, q) tail-cell groups; q are per-index conditional probabilities summing to 1."""
    t = w - P
    R = (1 << B) - 1  # max storable register value (B bits, register > 0)
    groups = []
    if t == B:
        for r in range(1, R):
            groups.append((1, 2.0 ** (-r)))
        groups.append((1, 2.0 ** (-(R - 1))))  # saturating register absorbs the tail
        return groups
    # wider width: flag bit + structure
    # flag 0: register <= B + 1, leading (t-1) bits stored verbatim, each cell q = 2^-(t-1)
    qv = 2.0 ** (-(t - 1))
    for l in range(0, min(B, t - 2) + 1):  # leading-zero run length l -> register r = l + 1 <= B+1
        groups.append((1 << (t - 2 - l), qv))
    # flag 1: register >= B + 2, residual of (t-1-B) bits
    res_bits = t - 1 - B
    res = 1 << res_bits
    for r in range(B + 2, R):  # non-saturating registers
        groups.append((res, 2.0 ** (-r) * 2.0 ** (-res_bits)))
    # saturating register r = R absorbs sum_{r>=R} 2^-r = 2^-(R-1)
    groups.append((res, 2.0 ** (-(R - 1)) * 2.0 ** (-res_bits)))
    return groups


def expected_D(n, P, groups):
    m = 1 << P
    total = 0.0
    for count, q in groups:
        p = q / m  # per-cell absolute probability
        total += count * (1.0 - (1.0 - p) ** n)
    return m * total


def invert(D, P, groups):
    """Solve E[D|n] = D for n by bisection on the monotone curve."""
    if D <= 0:
        return 0.0
    lo, hi = float(D), float(D)
    while expected_D(hi, P, groups) < D:
        hi *= 2.0
        if hi > 1e12:
            return hi
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if expected_D(mid, P, groups) < D:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def collision_q(P, groups):
    """P(two distinct elements share a composite at this width) = sum_c p_c^2."""
    m = 1 << P
    return sum(count * (q / m) ** 2 for count, q in groups)


def invert_with_duplicates(D_plus_dup, P, groups):
    """Estimator B: n - C(n,2)*q = number_of_hashes + duplicates (birthday silent-collision model)."""
    q = collision_q(P, groups)
    if D_plus_dup <= 0:
        return 0.0
    lo, hi = float(D_plus_dup), float(D_plus_dup)
    while hi - 0.5 * hi * (hi - 1.0) * q < D_plus_dup:
        hi *= 2.0
        if hi > 1e12:
            return hi
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if mid - 0.5 * mid * (mid - 1.0) * q < D_plus_dup:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def linear_counting_keff(D, P, groups):
    """Estimator C: linear counting with effective capacity K_eff = 1 / collision_probability.

    Needs only a logarithm (already available in the crate), no general exp. K_eff is the inverse
    participation ratio of the cell probabilities, the count of equally-likely cells that would give
    the same single-element collision rate.
    """
    keff = 1.0 / collision_q(P, groups)
    if D >= keff:
        return keff  # saturated; clamp
    import math

    return -keff * math.log(1.0 - D / keff)


def main():
    rows = defaultdict(list)
    with open(CSV) as f:
        for row in csv.DictReader(f):
            rows[(int(row["P"]), int(row["B"]))].append(
                (int(row["n"]), int(row["nhashes"]), int(row["dup"]), int(row["w"]))
            )

    # Sanity: tail masses sum to 1 at a few widths.
    for (P, B) in sorted(rows):
        for w in {min(r[3] for r in rows[(P, B)]), max(r[3] for r in rows[(P, B)])}:
            mass = sum(c * q for c, q in tail_groups(P, B, w))
            assert abs(mass - 1.0) < 1e-9, f"P{P}B{B} w{w} tail mass {mass}"

    print("A = full occupancy inverse on number_of_hashes   C = linear counting with K_eff = 1/collision_prob\n")
    print(f"{'cell':>7} {'bound':>7} | {'A_mean':>8} {'A_std':>7} {'A_tailstd':>9} {'A_max':>7} | "
          f"{'C_mean':>8} {'C_std':>7} {'C_tailstd':>9} {'C_max':>7}")
    cache = {}
    for (P, B) in sorted(rows):
        data = rows[(P, B)]
        bound = 1.04 / np.sqrt(1 << P)
        rels_a, rels_c, n_true_arr = [], [], []
        for (n, D, dup, w) in data:
            key = (P, B, w)
            if key not in cache:
                cache[key] = tail_groups(P, B, w)
            g = cache[key]
            rels_a.append((invert(D, P, g) - n) / n)
            rels_c.append((linear_counting_keff(D, P, g) - n) / n)
            n_true_arr.append(n)
        ra, rc = np.array(rels_a), np.array(rels_c)
        nt = np.array(n_true_arr, float)
        tail = nt >= 0.8 * nt.max()
        print(f"  P{P}B{B:<2} {bound:>7.4f} | {ra.mean():>+8.4f} {ra.std():>7.4f} {ra[tail].std():>9.4f} {np.abs(ra).max():>7.4f} | "
              f"{rc.mean():>+8.4f} {rc.std():>7.4f} {rc[tail].std():>9.4f} {np.abs(rc).max():>7.4f}")


if __name__ == "__main__":
    main()
