[package]
name = "bias_estimator"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperloglog-rs = {path = "../"}
indicatif = {version="0.17.8", features=["rayon"]}
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.205"
serde_json = "1.0.122"
twox-hash = "1.6.3"
wyhash = "0.5.0"
