[package]
name = "hyperloglog-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version="2.0", features=["full"]}
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0.127"

[lib]
proc-macro = true

[dev-dependencies]
hyperloglog-rs = { path = "../../hyperloglog-rs" }
