// Precomputed per-cell numerical table.
#![allow(clippy::unreadable_literal)]
//! Register-regime linear-counting threshold (generated by the `correction_coefficients` crate).
//!
//! The dense `HyperLogLog` register regime uses Ertl's analytical tau/sigma estimator in
//! `src/sigma_tau.rs` (no fitted polynomials, no anchor tables). What remains here is the
//! per-cell linear-counting crossover: below this cardinality the counter stays in the NaN-boxed
//! dense zeros mode and returns `m * ln(m / zeros)` in O(1); above it, `to_hll` and the insert
//! path transition to the packed harmonic mode where sigma/tau applies.
//!
//! The hash-list regime is estimated analytically by the width-aware occupancy inverse in
//! `src/hyperloglog.rs` (`HyperLogLog::hash_list_cardinality`).

/// The cardinality at or below which a force-dense `HyperLogLog` counter should report linear
/// counting instead of Ertl's tau/sigma estimate, indexed `[precision - 4][bits - 4]`.
pub(super) const HYPERLOGLOG_LINEAR_COUNT_THRESHOLD: [[u32; 3]; 15usize] = [
    [45u32, 45u32, 45u32],
    [54u32, 104u32, 104u32],
    [108u32, 128u32, 139u32],
    [202u32, 257u32, 299u32],
    [367u32, 490u32, 1272u32],
    [664u32, 902u32, 2880u32],
    [1332u32, 1804u32, 2320u32],
    [2632u32, 3576u32, 4592u32],
    [5280u32, 7088u32, 9184u32],
    [10464u32, 14208u32, 18240u32],
    [23744u32, 29184u32, 37120u32],
    [36480u32, 52352u32, 70912u32],
    [133120u32, 145408u32, 140288u32],
    [575488u32, 589824u32, 589824u32],
    [1376256u32, 1372160u32, 1372160u32],
];
