name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Addind baremetal arm target
        run: rustup target add aarch64-unknown-none
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --target x86_64-unknown-linux-gnu
      - name: Run clippy
        run: cargo clippy -- -Dclippy::all -Dclippy::cargo
